<?php $actions = [['/admin/pages/builder/toggle', null, 'subtle'], ['/admin/pages/builder/duplicate', 'Duplikuj', 'subtle'], ['/admin/pages/builder/delete', 'Usuń', 'danger-text']]; ?>
<div class="toolbar"><div><p class="eyebrow">Page builder</p><p class="lead"><code><?= $escape($identity->value()) ?></code></p></div><div class="actions"><a class="button secondary" href="/admin/pages/edit?path=<?= rawurlencode($identity->value()) ?>">Ustawienia strony</a><a class="button" href="/admin/pages/builder/picker?path=<?= rawurlencode($identity->value()) ?>">Dodaj blok</a><a class="button child" href="/admin/media?path=<?= rawurlencode($identity->value()) ?>">Multimedia</a></div></div>
<div class="builder-list" data-builder-list>
<?php if ($blocks === []): ?><div class="empty-state"><strong>Ta strona nie ma jeszcze bloków.</strong><p>Dodaj pierwszy blok, a formularz zostanie wygenerowany z jego definicji YAML.</p></div><?php endif; ?>
<?php foreach ($blocks as $block): ?>
    <article class="builder-item<?= $block['enabled'] ? '' : ' disabled' ?>" draggable="true" data-block-id="<?= $escape($block['id']) ?>"><button type="button" class="drag-handle" aria-label="Przeciągnij blok">⋮⋮</button><div class="block-summary"><span class="position"><?= $block['position'] ?></span><div><strong><?= $escape($block['name']) ?></strong><small><?= $escape($block['type']) ?> · <?= $block['enabled'] ? 'włączony' : 'wyłączony' ?></small></div></div><div class="block-actions"><a class="button secondary" href="/admin/pages/builder/edit?path=<?= rawurlencode($identity->value()) ?>&amp;id=<?= rawurlencode($block['id']) ?>">Edytuj</a>
    <?php foreach ($actions as [$url, $fixedLabel, $class]): $label = $fixedLabel ?? ($block['enabled'] ? 'Wyłącz' : 'Włącz'); ?><form method="post" action="<?= $url ?>"<?= $label === 'Usuń' ? ' data-confirm="Usunąć ten blok bezpowrotnie?"' : '' ?>><input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="identity" value="<?= $escape($identity->value()) ?>"><input type="hidden" name="id" value="<?= $escape($block['id']) ?>"><input type="hidden" name="revision" value="<?= $escape($revision->value()) ?>"><button type="submit" class="button <?= $class ?>"><?= $label ?></button></form><?php endforeach; ?></div></article>
<?php endforeach; ?>
</div>
<form class="order-form" method="post" action="/admin/pages/builder/reorder" data-order-form><input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="identity" value="<?= $escape($identity->value()) ?>"><input type="hidden" name="revision" value="<?= $escape($revision->value()) ?>"><span data-order-fields><?php foreach ($blocks as $block): ?><input type="hidden" name="order[]" value="<?= $escape($block['id']) ?>" data-order-field><?php endforeach; ?></span><button type="submit" class="button child" disabled data-order-submit>Zapisz kolejność</button></form>
