<div class="toolbar crud-toolbar"><div><p class="eyebrow">Biblioteka strony</p><p class="lead"><code><?= $escape($identity->value()) ?></code></p></div><a class="button secondary" href="/admin/pages/builder?path=<?= rawurlencode($identity->value()) ?>">Wróć do bloków</a></div>
<form class="media-upload" method="post" enctype="multipart/form-data" action="/admin/media/upload"><input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="identity" value="<?= $escape($identity->value()) ?>"><label><span>Dodaj plik</span><input type="file" name="media" required></label><div><button type="submit">Prześlij</button><small>Maksymalny rozmiar i typy określa <code>setup.yml</code>.</small></div></form>
<div class="media-grid">
<?php if ($items === []): ?><div class="empty-state media-empty"><strong>Brak multimediów tej strony.</strong><p>Prześlij pierwszy plik. Zostanie zapisany bezpośrednio obok <code>content.yml</code>.</p></div><?php endif; ?>
<?php foreach ($items as $entry): $item = $entry['item']; ?>
    <article class="media-card">
        <?php if ($item->isImage()): ?><img src="<?= $escape($entry['preview']) ?>" alt="" loading="lazy"><?php else: ?><div class="media-file-icon"><?= $escape(strtoupper(pathinfo($item->name()->value(), PATHINFO_EXTENSION))) ?></div><?php endif; ?>
        <div class="media-card-body"><strong title="<?= $escape($item->name()->value()) ?>"><?= $escape($item->name()->value()) ?></strong><small><?= $escape($item->mimeType()) ?> · <?= $escape($entry['size']) ?><?= $item->width() === null ? '' : ' · ' . $item->width() . '×' . $item->height() . ' px' ?></small><div class="media-card-actions"><?php if ($item->isImage()): ?><button class="button compact secondary" type="button" data-media-preview="<?= $escape($entry['url']) ?>" data-media-preview-name="<?= $escape($item->name()->value()) ?>">Podgląd</button><?php else: ?><a class="button compact secondary" href="<?= $escape($entry['url']) ?>" target="_blank" rel="noopener">Otwórz</a><?php endif; ?><form method="post" action="/admin/media/delete" data-confirm="Usunąć ten plik? Operacji nie można cofnąć."><input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="identity" value="<?= $escape($identity->value()) ?>"><input type="hidden" name="name" value="<?= $escape($item->name()->value()) ?>"><button type="submit" class="button compact danger-text">Usuń</button></form></div></div>
    </article>
<?php endforeach; ?>
</div>
<dialog class="media-lightbox" data-media-lightbox aria-label="Podgląd multimedia"><button type="button" class="media-lightbox-close" data-media-lightbox-close aria-label="Zamknij">×</button><figure><img data-media-lightbox-image alt=""><figcaption data-media-lightbox-caption></figcaption></figure></dialog>
