main:
  -
    label:
      pl: Architektura
      en: Architecture
    link:
      type: url
      url: '/#architektura'
    target: _self
    children: {}
  -
    label:
      pl: Dokumentacja
      en: Docs
    link:
      type: collection
      collection: documentation
    target: _self
    children: {}
  -
    label:
      pl: API
      en: API
    link:
      type: url
      url: /api/docs
    target: _blank
    children: {}
  -
    label:
      pl: Insights
      en: Insights
    link:
      type: collection
      collection: insights
    target: _self
    children: {}
  -
    label:
      pl: Kontakt
      en: Contact
    link:
      type: page
      page: contact
    target: _self
    children: {}
footer:
  -
    label:
      pl: Architektura
      en: Architecture
    link:
      type: url
      url: '/#architektura'
    target: _self
    children: {}
  -
    label:
      pl: 'Status API'
      en: API
    link:
      type: url
      url: /api/docs
    target: _blank
    children: {}
  -
    label:
      pl: Panel
      en: Panel
    link:
      type: url
      url: /admin
    target: _self
    children: {}
  -
    label:
      pl: Kontakt
      en: Contact
    link:
      type: page
      page: contact
    target: _self
    children: {}
